# src/main/resources/plugin.yml
name: BackpackMC
main: com.brandon10x15.backpackmc.BackpackMCPlugin
version: 1.0.1
api-version: 1.21
libraries:
  - com.mysql:mysql-connector-j:9.1.0
  - org.xerial:sqlite-jdbc:3.46.0.1
loadbefore:
  - Essentials
  - EssentialsX

commands:
  backpack:
    description: Open your backpack or manage settings
    usage: /backpack
    permission: backpackmc.backpack.use

  clearinventory:
    description: Clear inventory (confirmation if enabled)
    usage: /clearinventory [player]
    permission: backpackmc.clearInventory
  ci:
    description: Clear inventory (alias)
    usage: /ci [player]
    permission: backpackmc.clearInventory
  eci:
    description: Clear inventory (Essentials alias)
    usage: /eci [player]
    permission: backpackmc.clearInventory
  clean:
    description: Clear inventory (alias)
    usage: /clean [player]
    permission: backpackmc.clearInventory
  eclean:
    description: Clear inventory (Essentials alias)
    usage: /eclean [player]
    permission: backpackmc.clearInventory
  clear:
    description: Clear inventory (alias)
    usage: /clear [player]
    permission: backpackmc.clearInventory
  eclear:
    description: Clear inventory (Essentials alias)
    usage: /eclear [player]
    permission: backpackmc.clearInventory
  clearinvent:
    description: Clear inventory (alias)
    usage: /clearinvent [player]
    permission: backpackmc.clearInventory
  eclearinvent:
    description: Clear inventory (Essentials alias)
    usage: /eclearinvent [player]
    permission: backpackmc.clearInventory
  eclearinventory:
    description: Clear inventory (Essentials alias)
    usage: /eclearinventory [player]
    permission: backpackmc.clearInventory

  clearinventoryconfirmtoggle:
    description: Toggle clear inventory confirmation
    usage: /clearinventoryconfirmtoggle
  eclearinventoryconfirmtoggle:
    description: Toggle clear inventory confirmation (Essentials alias)
    usage: /eclearinventoryconfirmtoggle

  clearinventoryconfirmoff:
    description: Disable clear inventory confirmation
    usage: /clearinventoryconfirmoff
  eclearinventoryconfirmoff:
    description: Disable clear inventory confirmation (Essentials alias)
    usage: /eclearinventoryconfirmoff
  clearconfirmoff:
    description: Disable clear inventory confirmation
    usage: /clearconfirmoff
  eclearconfirmoff:
    description: Disable clear inventory confirmation (Essentials alias)
    usage: /eclearconfirmoff

  clearconfirmon:
    description: Enable clear inventory confirmation
    usage: /clearconfirmon
  eclearconfirmon:
    description: Enable clear inventory confirmation (Essentials alias)
    usage: /eclearconfirmon

  clearconfirm:
    description: Confirm pending inventory clear
    usage: /clearconfirm
  eclearconfirm:
    description: Confirm pending inventory clear (Essentials alias)
    usage: /eclearconfirm

permissions:
  backpackmc.backpack.use:
    description: Use backpack
    default: true
  backpackmc.backpack.noCooldown:
    description: Bypass backpack command cooldown
    default: op
  backpackmc.backpack.clean:
    description: Clean your backpack
    default: true
  backpackmc.backpack.clean.other:
    description: Clean others' backpacks
    default: op
  backpackmc.backpack.sort:
    description: Sort your backpack
    default: true
  backpackmc.backpack.autosort:
    description: Change auto-sort mode
    default: true
  backpackmc.backpack.reload:
    description: Reload plugin
    default: op
  backpackmc.backpack.update:
    description: Check for update
    default: op
  backpackmc.backpack.migrate:
    description: Migrate storage backend
    default: op
  backpackmc.backpack.others:
    description: Open others' backpacks
    default: op
  backpackmc.backpack.others.edit:
    description: Edit others' backpacks
    default: op
  backpackmc.backpack.ignoreWorldBlacklist:
    description: Ignore world blacklist
    default: op
  backpackmc.backpack.ignoreGameMode:
    description: Ignore restricted gamemodes
    default: op
  backpackmc.backpack.keepOnDeath:
    description: Keep backpack on death
    default: true
  backpackmc.backpack.fullpickup:
    description: Pickup to backpack when inventory is full
    default: true

  backpackmc.clearInventory:
    description: Clear your inventory
    default: true
  backpackmc.clearInventory.other:
    description: Clear others' inventories
    default: op
